"""Natural language to structured settings conversion API.

This API endpoint uses an LLM to convert natural language descriptions
into structured worker/project settings.

Prefers local Claude Code CLI, falls back to external APIs.
"""

import asyncio
import json
import logging
import os
import shutil
from typing import TYPE_CHECKING, Annotated

import httpx
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from ringmaster.api.deps import get_db
from ringmaster.db import Database

if TYPE_CHECKING:
    from ringmaster.domain import Worker

logger = logging.getLogger(__name__)
router = APIRouter()


class NLToSettingsRequest(BaseModel):
    """Request body for natural language to settings conversion."""

    natural_language: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Natural language description of desired settings",
    )
    settings_type: str = Field(
        default="worker",
        description="Type of settings to generate: 'worker', 'project', etc.",
    )


class WorkerSettingsFromAI(BaseModel):
    """Worker settings generated by AI."""

    name: str | None = None
    description: str | None = None
    type: str | None = None
    generated_script: str | None = None
    capabilities: list[str] | None = None
    reasoning: str | None = None

    # Legacy fields - deprecated, kept for backwards compatibility
    command: str | None = None
    args: list[str] | None = None
    prompt_flag: str | None = None
    working_dir: str | None = None
    timeout_seconds: int | None = None
    launcher_script: str | None = None
    launcher_args: list[str] | None = None
    launcher_script_inline: str | None = None
    env_vars: dict[str, str] | None = None


class NLToSettingsResponse(BaseModel):
    """Response from natural language to settings conversion."""

    success: bool
    settings: dict | None = None
    worker_settings: WorkerSettingsFromAI | None = None
    reasoning: str | None = None
    error: str | None = None


def get_llm_api_key() -> str | None:
    """Get the LLM API key from environment variables.

    Supports OpenAI or Anthropic APIs.
    """
    return os.getenv("OPENAI_API_KEY") or os.getenv("ANTHROPIC_API_KEY") or os.getenv("LLM_API_KEY")


def get_llm_provider() -> str:
    """Determine which LLM provider to use based on availability.

    Priority:
    1. Local Claude Code CLI (claude command)
    2. Anthropic API (ANTHROPIC_API_KEY)
    3. OpenAI API (OPENAI_API_KEY)
    """
    if shutil.which("claude"):
        return "claude-code-local"
    if os.getenv("ANTHROPIC_API_KEY"):
        return "anthropic"
    if os.getenv("OPENAI_API_KEY"):
        return "openai"
    if os.getenv("LLM_API_KEY"):
        return "openai"  # Default to OpenAI format
    return "none"


async def call_claude_code_local(prompt: str) -> str:
    """Call local Claude Code CLI to generate settings from natural language."""
    system_prompt = """You are a worker configuration assistant. Generate complete, self-contained worker bash scripts.

The worker script you generate should be a COMPLETE bash script that:
1. Starts with a shebang (#!/bin/bash)
2. Sets up any necessary environment variables
3. Implements proper signal handling (SIGINT, SIGTERM)
4. Polls for tasks from Ringmaster via HTTP API
5. Executes the AI coding tool (Claude Code, Aider, etc.)
6. Reports results back to Ringmaster
7. Has proper error handling and logging

IMPORTANT: Generate a FULLY self-contained script. Do NOT use placeholder variables or config sections. All worker behavior should be directly coded into the script.

Authentication - Support ALL methods:
- Monthly Plans (Claude Code Pro, Cursor Pro) - just call the tool directly
- API Keys - set as environment variables if mentioned
- Local CLI auth - tool uses its existing auth
- Config files - tool reads from ~/.config/

Return JSON with these fields:
- name: Worker name (string)
- description: Brief description (string)
- type: Worker type (string)
- generated_script: Complete bash script (string) - THIS IS THE MAIN FIELD
- capabilities: Array of capability tags (array of strings)

Example complete worker script for a Python backend developer:
#!/bin/bash
set -euo pipefail

WORKER_ID="\${1:-}"
RINGMASTER_API="http://localhost:8080/api"

log() {
    echo "[$(date -Iseconds)] [$WORKER_ID] \$*" >&2
}

trap 'log "Shutting down..."; exit 0' SIGINT SIGTERM

get_next_task() {
    curl -s "\${RINGMASTER_API}/workers/\${WORKER_ID}/next-task"
}

process_task() {
    local task_json="\$1"
    local task_id task_prompt working_dir

    task_id=\$(echo "\$task_json" | jq -r '.id')
    task_prompt=\$(echo "\$task_json" | jq -r '.prompt')
    working_dir=\$(echo "\$task_json" | jq -r '.working_dir // empty')

    log "Task: \$task_prompt"

    local work_dir="\${WORKING_DIR:-.}"
    if [ -n "\$working_dir" ] && [ -d "\$working_dir" ]; then
        work_dir="\$working_dir"
    fi

    cd "\$work_dir" || exit 1

    # Execute Claude Code for Python backend work
    # This worker specializes in FastAPI, Flask, SQLAlchemy
    claude --prompt "\${task_prompt}

Focus on Python backend development:
- Use FastAPI or Flask as appropriate
- Write SQLAlchemy models with proper relationships
- Create RESTful endpoints with proper error handling
- Add type hints throughout
- Include pytest tests
- Follow PEP 8 conventions
" || true

    # Report completion
    curl -s -X POST "\${RINGMASTER_API}/workers/\${WORKER_ID}/complete" \\
        -H "Content-Type: application/json" \\
        -d '{"task_id": "'\${task_id}'", "success": true}'
}

# Main loop
while true; do
    local task=\$(get_next_task)
    if [ "\$task" != "null" ] && [ -n "\$task" ]; then
        process_task "\$task"
    fi
    sleep 5
done

Notice: The worker behavior (Python backend specialization, preferred frameworks, coding style) is BAKED INTO THE script, not in a separate config variable.

Only include fields that are explicitly mentioned or implied. Return ONLY valid JSON, no markdown."""

    full_prompt = f"""{system_prompt}

Generate a complete worker bash script based on this description:

{prompt}

Return ONLY a valid JSON object with these fields:
- name: Worker name
- description: Brief description
- type: Worker type
- generated_script: Complete bash script (self-contained, no placeholders)
- capabilities: Array of capability tags

Do not include markdown formatting, explanations, or any text outside the JSON."""

    try:
        process = await asyncio.create_subprocess_exec(
            "claude",
            "--print",
            "--dangerously-skip-permissions",
            "-p",
            full_prompt,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        stdout, stderr = await asyncio.wait_for(
            process.communicate(),
            timeout=120.0,
        )

        if process.returncode != 0:
            error_msg = stderr.decode("utf-8", errors="replace")
            logger.error(f"Claude Code CLI failed: {error_msg}")
            raise HTTPException(
                status_code=500,
                detail=f"Claude Code CLI failed: {error_msg}",
            )

        result = stdout.decode("utf-8", errors="replace").strip()

        # Extract JSON from response (handle potential markdown wrapping)
        if "```json" in result:
            # Extract from code block
            start = result.find("```json") + 7
            end = result.rfind("```")
            result = result[start:end].strip()
        elif "```" in result:
            # Extract from generic code block
            start = result.find("```") + 3
            end = result.rfind("```")
            result = result[start:end].strip()

        # Log raw result for debugging
        logger.debug(f"LLM response (first 500 chars): {result[:500]}")

        # Validate JSON before returning
        try:
            json.loads(result)
        except json.JSONDecodeError as e:
            # Try to fix common JSON issues
            logger.warning(f"Invalid JSON from LLM: {e}, attempting repair")

            # Try to find JSON object boundaries
            start_idx = result.find("{")
            end_idx = result.rfind("}")

            if start_idx >= 0 and end_idx > start_idx:
                # Extract just the JSON object
                result = result[start_idx:end_idx + 1]

                # Unescape escaped newlines in strings (common issue with bash scripts)
                result = result.replace("\\n", "\n")
                result = result.replace("\\t", "\t")

                # Validate again
                try:
                    json.loads(result)
                    logger.info("JSON repair successful")
                except json.JSONDecodeError as e2:
                    logger.error(f"JSON repair failed: {e2}")
                    logger.debug(f"Attempted JSON (first 1000 chars): {result[:1000]}")
                    raise

        return result

    except asyncio.TimeoutError:
        if process:
            process.kill()
            await process.wait()
        raise HTTPException(status_code=500, detail="Claude Code CLI timed out")
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail="Claude Code CLI not found")


async def call_anthropic_api(prompt: str) -> str:
    """Call Anthropic Claude API to generate settings from natural language."""
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="Anthropic API key not configured")

    headers = {
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }

    system_prompt = """You are a worker configuration assistant. Generate complete, self-contained worker bash scripts.

The worker script you generate should be a COMPLETE bash script that:
1. Starts with a shebang (#!/bin/bash)
2. Sets up any necessary environment variables
3. Implements proper signal handling (SIGINT, SIGTERM)
4. Polls for tasks from Ringmaster via HTTP API
5. Executes the AI coding tool (Claude Code, Aider, etc.)
6. Reports results back to Ringmaster
7. Has proper error handling and logging

IMPORTANT: Generate a FULLY self-contained script. Do NOT use placeholder variables or config sections. All worker behavior should be directly coded into the script.

Authentication - Support ALL methods:
- Monthly Plans (Claude Code Pro, Cursor Pro) - just call the tool directly
- API Keys - set as environment variables if mentioned
- Local CLI auth - tool uses its existing auth
- Config files - tool reads from ~/.config/

Return JSON with these fields:
- name: Worker name (string)
- description: Brief description (string)
- type: Worker type (string)
- generated_script: Complete bash script (string) - THIS IS THE MAIN FIELD
- capabilities: Array of capability tags (array of strings)

Only include fields that are explicitly mentioned or implied. Return ONLY valid JSON, no markdown."""

    user_message = f"""Generate a complete worker bash script based on this description:

{prompt}

Return ONLY a valid JSON object with these fields:
- name: Worker name
- description: Brief description
- type: Worker type
- generated_script: Complete bash script
- capabilities: Array of capability tags

Do not include markdown formatting, explanations, or any text outside the JSON."""

    payload = {
        "model": "claude-3-5-sonnet-20241022",
        "max_tokens": 2000,
        "system": system_prompt,
        "messages": [{"role": "user", "content": user_message}],
    }

    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers=headers,
            json=payload,
        )
        response.raise_for_status()
        data = response.json()
        return data["content"][0]["text"]


async def call_openai_api(prompt: str) -> str:
    """Call OpenAI API to generate settings from natural language."""
    api_key = os.getenv("OPENAI_API_KEY") or os.getenv("LLM_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="OpenAI API key not configured")

    headers = {
        "Authorization": f"Bearer {api_key}",
        "content-type": "application/json",
    }

    system_prompt = """You are a worker configuration assistant. Generate complete, self-contained worker bash scripts.

The worker script you generate should be a COMPLETE bash script that:
1. Starts with a shebang (#!/bin/bash)
2. Sets up any necessary environment variables
3. Implements proper signal handling (SIGINT, SIGTERM)
4. Polls for tasks from Ringmaster via HTTP API
5. Executes the AI coding tool (Claude Code, Aider, etc.)
6. Reports results back to Ringmaster
7. Has proper error handling and logging

IMPORTANT: Generate a FULLY self-contained script. Do NOT use placeholder variables or config sections. All worker behavior should be directly coded into the script.

Authentication - Support ALL methods:
- Monthly Plans (Claude Code Pro, Cursor Pro) - just call the tool directly
- API Keys - set as environment variables if mentioned
- Local CLI auth - tool uses its existing auth
- Config files - tool reads from ~/.config/

Return JSON with these fields:
- name: Worker name (string)
- description: Brief description (string)
- type: Worker type (string)
- generated_script: Complete bash script (string) - THIS IS THE MAIN FIELD
- capabilities: Array of capability tags (array of strings)

Only include fields that are explicitly mentioned or implied. Return ONLY valid JSON, no markdown."""

    user_message = f"""Generate a complete worker bash script based on this description:

{prompt}

Return ONLY a valid JSON object with these fields:
- name: Worker name
- description: Brief description
- type: Worker type
- generated_script: Complete bash script
- capabilities: Array of capability tags

Do not include markdown formatting, explanations, or any text outside the JSON."""

    payload = {
        "model": "gpt-4o-mini",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "temperature": 0.3,
        "max_tokens": 2000,
    }

    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            "https://api.openai.com/v1/chat/completions",
            headers=headers,
            json=payload,
        )
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"]


@router.post("/nl-to-settings", response_model=NLToSettingsResponse)
async def natural_language_to_settings(
    db: Annotated[Database, Depends(get_db)],
    body: NLToSettingsRequest,
) -> NLToSettingsResponse:
    """Convert natural language description to structured settings.

    Priority:
    1. Local Claude Code CLI (claude command) - uses existing auth
    2. Anthropic API (ANTHROPIC_API_KEY)
    3. OpenAI API (OPENAI_API_KEY)

    Local Claude Code is preferred as it reuses your existing authentication
    and monthly plan if available.
    """
    provider = get_llm_provider()

    if provider == "none":
        logger.warning("No LLM provider available")
        return NLToSettingsResponse(
            success=False,
            error="No LLM provider available. Install Claude Code CLI, or set ANTHROPIC_API_KEY or OPENAI_API_KEY environment variable.",
        )

    try:
        # Try local Claude Code first
        if provider == "claude-code-local":
            logger.info(f"Using local Claude Code CLI for {body.settings_type} settings")
            result_text = await call_claude_code_local(body.natural_language)
        # Fall back to external APIs
        elif provider == "anthropic":
            logger.info(f"Calling Anthropic API for {body.settings_type} settings")
            result_text = await call_anthropic_api(body.natural_language)
        else:  # openai
            logger.info(f"Calling OpenAI API for {body.settings_type} settings")
            result_text = await call_openai_api(body.natural_language)

        # Clean up the response - remove markdown code blocks if present
        result_text = result_text.strip()
        if result_text.startswith("```"):
            # Remove markdown code block markers
            lines = result_text.split("\n")
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines[-1].startswith("```"):
                lines = lines[:-1]
            result_text = "\n".join(lines)

        # Parse JSON response
        settings_data = json.loads(result_text)

        # Create worker settings response
        worker_settings = WorkerSettingsFromAI(**settings_data)

        logger.info(f"Successfully generated {body.settings_type} settings from natural language")

        return NLToSettingsResponse(
            success=True,
            settings=settings_data,
            worker_settings=worker_settings,
            reasoning=worker_settings.reasoning,
        )

    except httpx.HTTPStatusError as e:
        logger.error(f"LLM API error: {e.response.status_code} - {e.response.text}")
        return NLToSettingsResponse(
            success=False,
            error=f"LLM API error: {e.response.status_code}",
        )
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse LLM response as JSON: {e}")
        logger.debug(f"LLM response text: {result_text}")
        return NLToSettingsResponse(
            success=False,
            error=f"Failed to parse LLM response as JSON: {str(e)}",
        )
    except Exception as e:
        logger.error(f"Error converting natural language to settings: {e}")
        return NLToSettingsResponse(
            success=False,
            error=str(e),
        )


@router.get("/ai-status")
async def get_ai_status() -> dict:
    """Check if LLM integration is configured and available authentication methods."""
    provider = get_llm_provider()
    api_key = get_llm_api_key()
    has_claude_cli = shutil.which("claude") is not None

    return {
        "enabled": has_claude_cli or api_key is not None,
        "provider": provider,
        "has_claude_cli": has_claude_cli,
        "has_api_key": api_key is not None,
        "auth_methods": {
            "local_claude_cli": has_claude_cli,  # Preferred - uses existing auth
            "api_key": api_key is not None,
            "monthly_plans": True,  # Workers can use monthly plans (Claude Code Pro, Cursor, Copilot)
            "cli_auth": True,      # Workers can use existing CLI authentication
            "config_files": True,  # Workers can use config file auth
        },
        "supported_methods": [
            "Local Claude Code CLI (preferred - uses your existing auth)",
            "Claude Code Pro/Team (claude command)",
            "Cursor Pro (cursor command)",
            "GitHub Copilot (copilot command)",
            "Aider (aider command)",
            "Anthropic API (ANTHROPIC_API_KEY)",
            "OpenAI API (OPENAI_API_KEY)",
        ],
    }


# =============================================================================
# Worker Creation/Update from Natural Language
# =============================================================================


class CreateWorkerFromNLRequest(BaseModel):
    """Request body for creating a worker from natural language."""

    natural_language: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Natural language description of the worker to create",
    )
    worker_id: str | None = Field(
        None,
        description="Optional custom worker ID (auto-generated if not provided)",
    )


class UpdateWorkerFromNLRequest(BaseModel):
    """Request body for updating a worker from natural language."""

    natural_language: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Natural language description of changes to make",
    )


async def call_claude_code_for_update(
    prompt: str,
    current_worker: "Worker | None" = None,  # type: ignore[name-defined]
) -> str:
    """Call local Claude Code CLI to generate worker updates.

    For updates, includes current worker state in the prompt.
    """
    base_prompt = """You are a worker configuration assistant. Generate complete, self-contained worker bash scripts.

The worker script you generate should be a COMPLETE bash script that:
1. Starts with a shebang (#!/bin/bash)
2. Sets up any necessary environment variables
3. Implements proper signal handling (SIGINT, SIGTERM)
4. Polls for tasks from Ringmaster via HTTP API
5. Executes the AI coding tool (Claude Code, Aider, etc.)
6. Reports results back to Ringmaster
7. Has proper error handling and logging

IMPORTANT: Generate a FULLY self-contained script. Do NOT use placeholder variables or config sections. All worker behavior should be directly coded into the script.

Authentication - Support ALL methods:
- Monthly Plans (Claude Code Pro, Cursor Pro) - just call the tool directly
- API Keys - set as environment variables if mentioned
- Local CLI auth - tool uses its existing auth
- Config files - tool reads from ~/.config/

Return JSON with these fields:
- name: Worker name (string)
- description: Brief description (string)
- type: Worker type (string)
- generated_script: Complete bash script (string) - THIS IS THE MAIN FIELD
- capabilities: Array of capability tags (array of strings)

Only include fields that are explicitly mentioned or implied. Return ONLY valid JSON, no markdown."""

    if current_worker:
        # For updates, include current worker state
        current_state = f"""
CURRENT WORKER STATE:
- Name: {current_worker.name}
- Description: {current_worker.description or 'None'}
- Type: {current_worker.type}
- Capabilities: {', '.join(current_worker.capabilities) if current_worker.capabilities else 'None'}
"""

        if current_worker.generated_script:
            current_state += f"\n- Has existing script: Yes ({len(current_worker.generated_script)} characters)"

        update_prompt = f"""{base_prompt}

{current_state}

USER REQUESTED CHANGES:
{prompt}

Generate an UPDATED worker configuration based on the current state and the requested changes.
Return ONLY a valid JSON object with the updated fields.
Fields not mentioned in the changes should keep their current values (or omit them).
"""
        full_prompt = update_prompt
    else:
        # For new workers
        full_prompt = f"""{base_prompt}

Generate a complete worker bash script based on this description:

{prompt}

Return ONLY a valid JSON object with these fields:
- name: Worker name
- description: Brief description
- type: Worker type
- generated_script: Complete bash script
- capabilities: Array of capability tags

Do not include markdown formatting, explanations, or any text outside the JSON."""

    try:
        process = await asyncio.create_subprocess_exec(
            "claude",
            "--print",
            "--dangerously-skip-permissions",
            "-p",
            full_prompt,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        stdout, stderr = await asyncio.wait_for(
            process.communicate(),
            timeout=120.0,
        )

        if process.returncode != 0:
            error_msg = stderr.decode("utf-8", errors="replace")
            logger.error(f"Claude Code CLI failed: {error_msg}")
            raise HTTPException(
                status_code=500,
                detail=f"Claude Code CLI failed: {error_msg}",
            )

        result = stdout.decode("utf-8", errors="replace").strip()

        # Extract JSON from response (handle potential markdown wrapping)
        if "```json" in result:
            start = result.find("```json") + 7
            end = result.rfind("```")
            result = result[start:end].strip()
        elif "```" in result:
            start = result.find("```") + 3
            end = result.rfind("```")
            result = result[start:end].strip()

        # Log raw result for debugging
        logger.debug(f"LLM response (first 500 chars): {result[:500]}")

        # Validate JSON before returning
        try:
            json.loads(result)
        except json.JSONDecodeError as e:
            # Try to fix common JSON issues
            logger.warning(f"Invalid JSON from LLM: {e}, attempting repair")

            # Try to find JSON object boundaries
            start_idx = result.find("{")
            end_idx = result.rfind("}")

            if start_idx >= 0 and end_idx > start_idx:
                # Extract just the JSON object
                result = result[start_idx:end_idx + 1]

                # Unescape escaped newlines in strings (common issue with bash scripts)
                result = result.replace("\\n", "\n")
                result = result.replace("\\t", "\t")

                # Validate again
                try:
                    json.loads(result)
                    logger.info("JSON repair successful")
                except json.JSONDecodeError as e2:
                    logger.error(f"JSON repair failed: {e2}")
                    logger.debug(f"Attempted JSON (first 1000 chars): {result[:1000]}")
                    raise

        return result

    except asyncio.TimeoutError:
        if process:
            process.kill()
            await process.wait()
        raise HTTPException(status_code=500, detail="Claude Code CLI timed out")
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail="Claude Code CLI not found")


@router.post("/create-worker", status_code=201)
async def create_worker_from_nl(
    db: Annotated[Database, Depends(get_db)],
    body: CreateWorkerFromNLRequest,
) -> NLToSettingsResponse:
    """Create a new worker from natural language description.

    This endpoint combines:
    1. AI generation of worker settings from natural language
    2. Worker creation in the database

    Example request:
    {
        "natural_language": "Create a Python testing worker that uses pytest",
        "worker_id": "pytest-worker-1"  // optional
    }

    The AI will generate:
    - Worker name and description
    - Worker type (claude-code, aider, generic, etc.)
    - Complete bash script for the worker
    - Capabilities for task matching
    """
    provider = get_llm_provider()

    if provider == "none":
        return NLToSettingsResponse(
            success=False,
            error="No LLM provider available. Install Claude Code CLI, or set ANTHROPIC_API_KEY or OPENAI_API_KEY environment variable.",
        )

    try:
        # Generate worker settings using local Claude Code
        logger.info(f"Generating worker settings from natural language")
        result_text = await call_claude_code_for_update(body.natural_language)

        # Parse JSON response
        settings_data = json.loads(result_text)
        worker_settings = WorkerSettingsFromAI(**settings_data)

        # Create worker in database
        from ringmaster.db import WorkerRepository
        from ringmaster.domain import Worker, WorkerStatus

        worker_repo = WorkerRepository(db)

        # Generate worker ID if not provided
        worker_id = body.worker_id or f"worker-{worker_settings.name.lower().replace(' ', '-')}"

        # Check if worker already exists
        existing = await worker_repo.get(worker_id)
        if existing:
            return NLToSettingsResponse(
                success=False,
                error=f"Worker {worker_id} already exists. Use update endpoint to modify.",
            )

        worker = Worker(
            id=worker_id,
            name=worker_settings.name or worker_id,
            description=worker_settings.description,
            type=worker_settings.type or "generic",
            generated_script=worker_settings.generated_script,
            capabilities=worker_settings.capabilities or [],
            status=WorkerStatus.OFFLINE,
        )

        created_worker = await worker_repo.create(worker)

        logger.info(f"Worker created from NL: id={created_worker.id}, name={created_worker.name}")

        return NLToSettingsResponse(
            success=True,
            settings=settings_data,
            worker_settings=worker_settings,
        )

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse LLM response as JSON: {e}")
        logger.debug(f"LLM response text: {result_text}")
        return NLToSettingsResponse(
            success=False,
            error=f"Failed to parse LLM response as JSON: {str(e)}",
        )
    except Exception as e:
        logger.error(f"Error creating worker from NL: {e}")
        return NLToSettingsResponse(
            success=False,
            error=str(e),
        )


@router.post("/update-worker/{worker_id}")
async def update_worker_from_nl(
    worker_id: str,
    db: Annotated[Database, Depends(get_db)],
    body: UpdateWorkerFromNLRequest,
) -> NLToSettingsResponse:
    """Update an existing worker from natural language description.

    This endpoint combines:
    1. AI interpretation of natural language changes
    2. Worker update in the database

    Example request:
    {
        "natural_language": "Add TypeScript capabilities and change description to focus on frontend"
    }

    The AI will:
    - Parse the current worker state
    - Apply the requested changes
    - Generate updated settings
    - Update the worker in the database
    """
    from ringmaster.db import WorkerRepository
    from ringmaster.domain import Worker

    provider = get_llm_provider()

    if provider == "none":
        return NLToSettingsResponse(
            success=False,
            error="No LLM provider available. Install Claude Code CLI, or set ANTHROPIC_API_KEY or OPENAI_API_KEY environment variable.",
        )

    # Get current worker
    worker_repo = WorkerRepository(db)
    current_worker = await worker_repo.get(worker_id)

    if not current_worker:
        return NLToSettingsResponse(
            success=False,
            error=f"Worker {worker_id} not found",
        )

    try:
        # Generate updated settings using local Claude Code with current state
        logger.info(f"Generating worker updates from natural language for {worker_id}")
        result_text = await call_claude_code_for_update(body.natural_language, current_worker)

        # Parse JSON response
        settings_data = json.loads(result_text)
        new_settings = WorkerSettingsFromAI(**settings_data)

        # Update worker with only the fields that were returned
        if new_settings.name is not None:
            current_worker.name = new_settings.name
        if new_settings.description is not None:
            current_worker.description = new_settings.description
        if new_settings.type is not None:
            current_worker.type = new_settings.type
        if new_settings.generated_script is not None:
            current_worker.generated_script = new_settings.generated_script
        if new_settings.capabilities is not None:
            current_worker.capabilities = new_settings.capabilities

        # Save to database
        updated_worker = await worker_repo.update(current_worker)

        logger.info(f"Worker updated from NL: id={updated_worker.id}, name={updated_worker.name}")

        return NLToSettingsResponse(
            success=True,
            settings=settings_data,
            worker_settings=new_settings,
        )

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse LLM response as JSON: {e}")
        logger.debug(f"LLM response text: {result_text}")
        return NLToSettingsResponse(
            success=False,
            error=f"Failed to parse LLM response as JSON: {str(e)}",
        )
    except Exception as e:
        logger.error(f"Error updating worker from NL: {e}")
        return NLToSettingsResponse(
            success=False,
            error=str(e),
        )
